#!/bin/bash

if [ $# -lt 2 ];then 
    echo ERROR: two parameters expected
    exit 1
else
    numbers=$1;
    cpus=$2;
fi;

#preklad cpp zdrojaku
mpic++ --prefix /usr/local/share/OpenMPI -o mss mss.cpp -std=c++11

#vyrobeni souboru s random cisly
dd if=/dev/urandom bs=1 count=$numbers 2>/dev/null 1>numbers
#spusteni
mpirun --prefix /usr/local/share/OpenMPI -np $cpus mss

#uklid
rm -f mss numbers
